name: survey_map
description: A Flutter application for radiological survey mapping
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # PDF rendering
  pdfx: ^2.6.0

  # PDF creation
  pdf: ^3.10.7
  printing: ^5.11.1

  # File picking
  file_picker: ^6.1.1

  # SVG rendering
  flutter_svg: ^2.0.9

  # State management
  provider: ^6.1.1

  # Image export
  image: ^4.1.3

  # Path operations
  path_provider: ^2.1.1
  vector_graphics: ^1.1.19

  # HTTP requests for web
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/Postings/
    - assets/postings.json
    - assets/building_maps.json
    - Current Maps/Building 200/
    - Current Maps/Building 203/
    - Current Maps/Building 205/
    - Current Maps/Building 206/
    - Current Maps/Building 211/
    - Current Maps/Building 212/
    - Current Maps/Building 242/
    - Current Maps/Building 306/
    - Current Maps/Building 308/
    - Current Maps/Building 315/
    - Current Maps/Building 316/
    - Current Maps/Building 350/
    - Current Maps/Building 367/
    - Current Maps/Building 400/
